webapp/src/Entity/Testcase.php
<?php declare(strict_types=1);
namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;

/**
 * Stores testcases per problem.
 */
#[ORM\Entity]
#[ORM\Table(options: [
    'collation' => 'utf8mb4_unicode_ci',
    'charset' => 'utf8mb4',
    'comment' => 'Stores testcases per problem',
])]
#[ORM\Index(columns: ['probid'], name: 'probid')]
#[ORM\Index(columns: ['sample'], name: 'sample')]
#[ORM\UniqueConstraint(name: 'rankindex', columns: ['probid', 'ranknumber'])]
class Testcase
{
    // Mapping from type to extension
    final public const EXTENSION_MAPPING = [
        'input'  => 'in',
        'output' => 'ans',
    ];

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(options: ['comment' => 'Testcase ID', 'unsigned' => true])]
    private int $testcaseid;

    #[ORM\Column(
        length: 32,
        nullable: true,
        options: ['comment' => 'Checksum of input data', 'fixed' => true]
    )]
    private ?string $md5sum_input = null;

    #[ORM\Column(
        length: 32,
        nullable: true,
        options: ['comment' => 'Checksum of output data', 'fixed' => true]
    )]
    private ?string $md5sum_output = null;

    #[ORM\Column(options: ['comment' => 'Determines order of the testcases in judging', 'unsigned' => true])]
    private int $ranknumber;

    /**
     * @var resource|null
     */
    #[ORM\Column(type: 'blob', nullable: true, options: ['comment' => 'Description of this testcase'])]
    #[Serializer\Exclude]
    private $description;

    private ?string $description_as_string = null;

    #[ORM\Column(
        nullable: true,
        options: ['comment' => 'Original basename of the input file.', 'default' => null]
    )]
    #[Serializer\Exclude]
    private ?string $orig_input_filename = null;

    #[ORM\Column(
        length: 4,
        nullable: true,
        options: ['comment' => 'File type of the image and thumbnail']
    )]
    #[Serializer\Exclude]
    private ?string $image_type = null;

    #[ORM\Column(options: [
        'comment' => 'Sample testcases that can be shared with teams',
        'default' => 0,
    ])]
    #[Serializer\Exclude]
    private bool $sample = false;

    #[ORM\Column(options: [
        'comment' => 'Deleted testcases are kept for referential integrity.',
        'default' => 0,
    ])]
    #[Serializer\Exclude]
    private bool $deleted = false;

    /**
     * @var Collection<int, JudgingRun>
     */
    #[ORM\OneToMany(mappedBy: 'testcase', targetEntity: JudgingRun::class)]
    #[Serializer\Exclude]
    private Collection $judging_runs;

    /**
     * @var Collection<int, ExternalRun>>
     */
    #[ORM\OneToMany(mappedBy: 'testcase', targetEntity: ExternalRun::class)]
    #[Serializer\Exclude]
    private Collection $external_runs;

    /**
     * @var Collection<int, TestcaseContent>
     *
     * We use a OneToMany instead of a OneToOne here, because otherwise this
     * relation will always be loaded. See the commit message of commit
     * 9e421f96691ec67ed62767fe465a6d8751edd884 for a more elaborate explanation.
     */
    #[ORM\OneToMany(mappedBy: 'testcase', targetEntity: TestcaseContent::class, cascade: ['persist'], orphanRemoval: true)]
    #[Serializer\Exclude]
    private Collection $content;

    #[ORM\ManyToOne(inversedBy: 'testcases')]
    #[ORM\JoinColumn(name: 'probid', referencedColumnName: 'probid', onDelete: 'CASCADE')]
    #[Serializer\Exclude]
    private ?Problem $problem = null;

    public function __construct()
    {
        $this->judging_runs  = new ArrayCollection();
        $this->external_runs = new ArrayCollection();
        $this->content       = new ArrayCollection();
    }

    public function getTestcaseid(): int
    {
        return $this->testcaseid;
    }

    public function setMd5sumInput(string $md5sumInput): Testcase
    {
        $this->md5sum_input = $md5sumInput;
        return $this;
    }

    public function getMd5sumInput(): string
    {
        return $this->md5sum_input;
    }

    public function setMd5sumOutput(string $md5sumOutput): Testcase
    {
        $this->md5sum_output = $md5sumOutput;
        return $this;
    }

    public function getMd5sumOutput(): string
    {
        return $this->md5sum_output;
    }

    public function setRank(int $rank): Testcase
    {
        $this->ranknumber = $rank;
        return $this;
    }

    public function getRank(): int
    {
        return $this->ranknumber;
    }

    /**
     * @param resource|string $description
     */
    public function setDescription($description): Testcase
    {
        $this->description = $description;
        return $this;
    }

    /**
     * @return resource|string|null
     */
    public function getDescription(bool $asString = false)
    {
        if ($asString && $this->description !== null) {
            if ($this->description_as_string === null) {
                $this->description_as_string = stream_get_contents($this->description);
            }
            return $this->description_as_string;
        }
        return $this->description;
    }

    public function setOrigInputFilename(string $origInputFilename): Testcase
    {
        $this->orig_input_filename = $origInputFilename;
        return $this;
    }

    public function getOrigInputFilename(): ?string
    {
        return $this->orig_input_filename;
    }

    public function setImageType(string $imageType): Testcase
    {
        $this->image_type = $imageType;
        return $this;
    }

    public function getImageType(): ?string
    {
        return $this->image_type;
    }

    public function setSample(bool $sample): Testcase
    {
        $this->sample = $sample;
        return $this;
    }

    public function setDeleted(bool $deleted): Testcase
    {
        $this->deleted = $deleted;
        return $this;
    }

    public function getSample(): bool
    {
        return $this->sample;
    }

    public function getDeleted(): bool
    {
        return $this->deleted;
    }

    public function addJudgingRun(JudgingRun $judgingRun): Testcase
    {
        $this->judging_runs[] = $judgingRun;
        return $this;
    }

    /**
     * @return Collection<int, JudgingRun>
     */
    public function getJudgingRuns(): Collection
    {
        return $this->judging_runs;
    }

    /**
     * Gets the first judging run for this testcase.
     *
     * This is useful when this testcase is joined to a single run to get code completion in Twig templates.
     */
    public function getFirstJudgingRun(): ?JudgingRun
    {
        return $this->judging_runs->first() ?: null;
    }

    /**
     * Gets the first external run for this testcase.
     *
     * This is useful when this testcase is joined to a single external run to get code completion in Twig templates.
     */
    public function getFirstExternalRun(): ?ExternalRun
    {
        return $this->external_runs->first() ?: null;
    }

    public function setContent(?TestcaseContent $content): Testcase
    {
        $this->content->clear();
        $this->content->add($content);
        $content->setTestcase($this);

        return $this;
    }

    public function getContent(): ?TestcaseContent
    {
        return $this->content->first() ?: null;
    }

    public function setProblem(?Problem $problem = null): Testcase
    {
        $this->problem = $problem;
        return $this;
    }

    public function getProblem(): ?Problem
    {
        return $this->problem;
    }

    public function addExternalRun(ExternalRun $externalRun): Testcase
    {
        $this->external_runs[] = $externalRun;
        return $this;
    }

    /**
     * @return Collection<int, ExternalRun>
     */
    public function getExternalRuns(): Collection
    {
        return $this->external_runs;
    }

    public function getDownloadName(): string
    {
        if ($this->getOrigInputFilename()) {
            return $this->getOrigInputFilename();
        }

        return sprintf('p%d.t%d', $this->getProblem()->getProbid(), $this->getRank());
    }
}

webapp/src/Controller/Jury/AnalysisController.php
<?php declare(strict_types=1);

namespace App\Controller\Jury;

use App\Entity\Judging;
use App\Entity\Problem;
use App\Entity\Submission;
use App\Entity\Team;
use App\Service\DOMJudgeService;
use App\Service\StatisticsService;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Query\Expr;
use Symfony\Bridge\Doctrine\Attribute\MapEntity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Attribute\MapQueryParameter;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_JURY')]
#[Route(path: '/jury/analysis')]
class AnalysisController extends AbstractController
{
    public function __construct(
        private readonly DOMJudgeService $dj,
        private readonly StatisticsService $stats,
        private readonly EntityManagerInterface $em
    ) {}

    #[Route(path: '', name: 'analysis_index')]
    public function indexAction(
        #[MapQueryParameter]
        ?string $view = null
    ): Response {
        $em = $this->em;
        $contest = $this->dj->getCurrentContest();

        if ($contest === null) {
            return $this->render('jury/error.html.twig', [
                'error' => 'No contest selected',
            ]);
        }

        $filterKeys = array_keys(StatisticsService::FILTERS);
        $view = $view ?: reset($filterKeys);

        $problems = $this->stats->getContestProblems($contest);
        $teams = $this->stats->getTeams($contest, $view);
        $misc = $this->stats->getMiscContestStatistics($contest, $teams, $view);

        $maxDelayedJudgings = 10;
        $delayedTimeDiff = 5;
        /** @var array<array{'submitid': int, 'judgingid': int, 'submittime': float,
         *                   'timediff': float, 'num_judgings': int}> $delayedJudgings */
        $delayedJudgings = $em->createQueryBuilder()
            ->from(Submission::class, 's')
            ->innerJoin(Judging::class, 'j', Expr\Join::WITH, 's.submitid = j.submission')
            ->select('s.submitid, MIN(j.judgingid) AS judgingid, s.submittime, MIN(j.starttime) - s.submittime AS timediff, COUNT(j.judgingid) AS num_judgings')
            ->andWhere('s.contest = :contest')
            ->setParameter('contest', $contest)
            ->andWhere('s.team IN (:teams)')
            ->setParameter('teams', $teams)
            ->groupBy('s.submitid')
            ->andHaving('timediff > :timediff')
            ->setParameter('timediff', $delayedTimeDiff)
            ->orderBy('timediff', 'DESC')
            ->getQuery()->getResult();

        return $this->render('jury/analysis/contest_overview.html.twig', [
            'contest' => $contest,
            'problems' => $problems,
            'teams' => $teams,
            'submissions' => $misc['submissions'],
            'delayed_judgings' => [
                'data' => array_slice($delayedJudgings, 0, $maxDelayedJudgings),
                'overflow' => count($delayedJudgings) - $maxDelayedJudgings,
                'delay' => $delayedTimeDiff,
            ],
            'misc' => $misc,
            'filters' => StatisticsService::FILTERS,
            'view' => $view,
        ]);
    }

    #[Route(path: '/team/{team}', name: 'analysis_team')]
    public function teamAction(Team $team): Response
    {
        $contest = $this->dj->getCurrentContest();

        if ($contest === null) {
            return $this->render('jury/error.html.twig', [
                'error' => 'No contest selected',
            ]);
        }

        return $this->render('jury/analysis/team.html.twig',
            $this->stats->getTeamStats($contest, $team)
        );
    }

    #[Route(path: '/problem/{probid}', name: 'analysis_problem')]
    public function problemAction(
        #[MapEntity(id: 'probid')]
        Problem $problem,
        #[MapQueryParameter]
        ?string $view = null
    ): Response {
        $contest = $this->dj->getCurrentContest();

        if ($contest === null) {
            return $this->render('jury/error.html.twig', [
                'error' => 'No contest selected',
            ]);
        }

        $filterKeys = array_keys(StatisticsService::FILTERS);
        $view = $view ?: reset($filterKeys);

        return $this->render('jury/analysis/problem.html.twig',
            $this->stats->getProblemStats($contest, $problem, $view)
        );
    }

    #[Route(path: '/languages', name: 'analysis_languages')]
    public function languagesAction(
        #[MapQueryParameter]
        ?string $view = null
    ): Response {
        $contest = $this->dj->getCurrentContest();

        if ($contest === null) {
            return $this->render('jury/error.html.twig', [
                'error' => 'No contest selected',
            ]);
        }

        $filterKeys = array_keys(StatisticsService::FILTERS);
        $view = $view ?: reset($filterKeys);

        return $this->render('jury/analysis/languages.html.twig',
            $this->stats->getLanguagesStats($contest, $view)
        );
    }
}

webapp/src/Controller/Jury/JudgeRemainingTrait.php
<?php declare(strict_types=1);

namespace App\Controller\Jury;

use App\Entity\JudgeTask;
use App\Entity\Judging;
use App\Entity\QueueTask;

trait JudgeRemainingTrait
{
    /**
     * @param Judging[] $judgings
     */
    protected function judgeRemaining(array $judgings): void
    {
        $inProgress = [];
        $alreadyRequested = [];
        $invalidJudgings = [];
        $numRequested = 0;
        foreach ($judgings as $judging) {
            $judgingId = $judging->getJudgingid();
            if ($judging->getResult() === null) {
                $inProgress[] = $judgingId;
            } elseif ($judging->getJudgeCompletely()) {
                $alreadyRequested[] = $judgingId;
            } elseif (!$judging->getValid()) {
                $invalidJudgings[] = $judgingId;
            } else {
                $numRequested = $this->em->getConnection()->executeStatement(
                    'UPDATE judgetask SET valid=1'
                    . ' WHERE jobid=:jobid'
                    . ' AND judgehostid IS NULL',
                    [
                        'jobid' => $judgingId,
                    ]
                );
                $judging->setJudgeCompletely(true);

                $submission = $judging->getSubmission();

                $queueTask = new QueueTask();
                $queueTask->setJudging($judging)
                    ->setPriority(JudgeTask::PRIORITY_LOW)
                    ->setTeam($submission->getTeam())
                    ->setTeamPriority((int)$submission->getSubmittime())
                    ->setStartTime(null);
                $this->em->persist($queueTask);
            }
        }
        $this->em->flush();
        if (count($judgings) === 1) {
            if ($inProgress !== []) {
                $this->addFlash('warning', 'Please be patient, this judging is still in progress.');
            }
            if ($alreadyRequested !== []) {
                $this->addFlash('warning', 'This judging was already requested to be judged completely.');
            }
        } else {
            if ($inProgress !== []) {
                $this->addFlash('warning', sprintf('Please be patient, these judgings are still in progress: %s', implode(', ', $inProgress)));
            }
            if ($alreadyRequested !== []) {
                $this->addFlash('warning', sprintf('These judgings were already requested to be judged completely: %s', implode(', ', $alreadyRequested)));
            }
            if ($invalidJudgings !== []) {
                $this->addFlash('warning', sprintf('These judgings were skipped as they were superseded by other judgings: %s', implode(', ', $invalidJudgings)));
            }
        }
        if ($numRequested === 0) {
            $this->addFlash('warning', 'No more remaining runs to be judged.');
        } else {
            $this->addFlash('info', "Requested $numRequested remaining runs to be judged.");
        }
    }
}

webapp/src/Controller/Jury/ScoreboardController.php
<?php declare(strict_types=1);

namespace App\Controller\Jury;

use App\Service\DOMJudgeService;
use App\Service\ScoreboardService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\ExpressionLanguage\Expression;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted(new Expression("is_granted('ROLE_JURY') or is_granted('ROLE_BALLOON')"))]
#[Route(path: '/jury/scoreboard')]
class ScoreboardController extends AbstractController
{
    public function __construct(protected readonly DOMJudgeService $dj, protected readonly ScoreboardService $scoreboardService)
    {
    }

    #[Route(path: '', name: 'jury_scoreboard')]
    public function scoreboardAction(Request $request): Response
    {
        $response   = new Response();
        $refreshUrl = $this->generateUrl('jury_scoreboard');
        $contest    = $this->dj->getCurrentContest();
        $data       = $this->scoreboardService->getScoreboardTwigData(
            $request, $response, $refreshUrl, $this->isGranted('ROLE_JURY'), false, false, $contest
        );

        if ($request->isXmlHttpRequest()) {
            $data['current_contest'] = $contest;
            return $this->render('partials/scoreboard.html.twig', $data, $response);
        }
        return $this->render('jury/scoreboard.html.twig', $data, $response);
    }
}

webapp/templates/jury/clarification_new.html.twig
{% extends "jury/base.html.twig" %}

{% block title %}Send clarification - {{ parent() }}{% endblock %}

{% block extrahead %}
    {{ parent() }}
{% endblock %}

{% block content %}

<div class="container clarificationform">
<h1>Send Clarification</h1>
{%- include 'jury/partials/clarification_form.html.twig'  %}
</div>

{% endblock %}

{% block extrafooter %}
    <script>
        $(function () {
            setupPreviewClarification($('#jury_clarification_message') , $('#messagepreview'), true);
        });
    </script>
{% endblock %}

webapp/templates/jury/contest_add.html.twig
{% extends "jury/base.html.twig" %}
{% import "jury/jury_macros.twig" as macros %}

{% block title %}Add contest - {{ parent() }}{% endblock %}

{% block extrahead %}
    {{ parent() }}
    {{ macros.select2_extrahead() }}
    {{ macros.coloris_extrahead() }}
{% endblock %}

{% block content %}

    <h1>Add contest</h1>

    {% include 'jury/partials/contest_form.html.twig' %}

    {{ macros.collection_scripts() }}

{% endblock %}

webapp/templates/jury/delete_modal.html.twig
{% extends "partials/modal.html.twig" %}

{% block title %}Delete {{ type }} {{ primaryKey }} - "{{ description }}"{% endblock %}

{% block content %}

    {% if isError %}
        <div class="alert alert-danger">
            <strong>Error: {{ messages.0 }}</strong>
        </div>
    {% else %}
        <p>You're about to delete {{ type }} {{ primaryKey }} "{{ description }}".</p>

        {% if messages is not empty %}
            <p>
                <strong>Warning, this will:</strong>
            </p>
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}

        <p>Are you sure?</p>
    {% endif %}

{% endblock %}

{% block closeButtonText %}
    {% if isError %}OK{% else %}Cancel{% endif %}
{% endblock %}

{% block buttonText %}Delete{% endblock %}

webapp/templates/jury/judgehosts_edit_multiple.html.twig
{% extends "jury/base.html.twig" %}

{% block title %}Edit Judgehosts - {{ parent() }}{% endblock %}

{% block content %}

    <h1>Edit Judgehosts</h1>

    {% include 'jury/partials/judgehosts_form.html.twig' %}

{% endblock %}

webapp/templates/jury/print.html.twig
{% extends "jury/base.html.twig" %}

{% block title %}Print - {{ parent() }}{% endblock %}

{% block content %}

    <div class="container submitform">
        <h1 class="text-center">Print source</h1>
        {{ form(form) }}
    </div>

{% endblock %}

{% block extrafooter %}
    {% include 'partials/javascript_print.html.twig' %}
{% endblock %}

webapp/templates/jury/problem_testcases.html.twig
{% extends "jury/base.html.twig" %}
{% import "jury/jury_macros.twig" as macros %}

{% block title %}Testcases for p{{ problem.probid }} - {{ parent() }}{% endblock %}

{% block extrahead %}
    {{ parent() }}
    {{ macros.table_extrahead() }}
{% endblock %}

{% block content %}

    <h1>Testcases for p{{ problem.probid }} - {{ problem.name }}</h1>

    <div class="mb-2">
        <a href="{{ path('jury_problem', {'probId': problem.probid}) }}">Back to problem p{{ problem.probid }}</a>
    </div>

    <form method="post" enctype="multipart/form-data">

    {% if testcases is empty %}
        <p class="nodata">No testcase(s) yet.</p>
    {% else %}
        <table class="table table-sm table-striped table-hover testcases">
            <thead>
            <tr>
                {% if allowEdit %}
                    <th></th>
                {% endif %}
                <th class="testrank">#</th>
                <th class="testsample">sample</th>
                <th>download</th>
                <th>size</th>
                <th>md5</th>
                {% if allowEdit %}
                    <th>upload new</th>
                {% endif %}
                <th>description / image</th>
            </tr>
            </thead>
            <tbody>
            {% for rank, testcase in testcases %}
                <tr>
                    {% if allowEdit %}
                        <td rowspan="2">
                            <a href="{{  path('jury_testcase_delete', {'testcaseId': testcase.testcaseid}) }}"
                               title="delete testcase {{ testcase.testcaseid }}"
                               onclick="confirm('Proceed with the deletion of testcase {{ testcase.testcaseid }}?');">
                                <i class="fas fa-trash-alt"></i>
                            </a>
                        </td>
                    {% endif %}
                    <td rowspan="2" class="testrank">
                        {% if allowEdit %}
                            <a href="{{ path('jury_problem_testcase_move', {'probId': problem.probid, 'rank': testcase.rank, 'direction': 'up'}) }}"
                               title="Move testcase up"><i class="fas fa-arrow-up"></i></a><br>
                        {% endif %}
                        {{ testcase.rank }}
                        {% if allowEdit %}
                            <br>
                            <a href="{{ path('jury_problem_testcase_move', {'probId': problem.probid, 'rank': testcase.rank, 'direction': 'down'}) }}"
                               title="Move testcase down"><i class="fas fa-arrow-down"></i></a>
                        {% endif %}
                    </td>
                    <td rowspan="2" class="testsample">
                        <input type="checkbox" name="sample[{{ testcase.rank }}]" value="sample"
                               {% if testcase.sample %}checked{% endif %} />
                    </td>
                    <td class="filename">
                        <a href="{{ path('jury_problem_testcase_fetch', {'probId': problem.probid, 'rank': testcase.rank, 'type': 'input'}) }}">
                            {{ testcase.downloadName }}.{{ extensionMapping.input }}
                        </a>
                    </td>
                    <td class="size">
                        {{ testcaseData[testcase.rank].input_size | printSize }}
                    </td>
                    <td class="md5 small">
                        {{ testcase.md5sumInput }}
                    </td>
                    {% if allowEdit %}
                        <td><div class="input-group">
                            <label class="form-control text-truncate" for="update_input_{{testcase.rank}}" id="update_input_label_{{testcase.rank}}">new input file</label>
                            <input type="file" class="d-none custom-file-input" name="update_input[{{ testcase.rank }}]" id="update_input_{{testcase.rank}}">
                        </div></td>
                    {% endif %}
                    <td class="testdesc">
                        <span class="testcase-description">{{ testcase.description(true) | descriptionExpand }}</span>
                        {% if allowEdit %}
                            <textarea class="d-none form-control testcase-description-field" name="description[{{ testcase.rank }}]">{{ testcase.description(true) }}</textarea>
                            <button type="button" class="float-end testcase-edit-description btn btn-secondary btn-sm">Edit</button>
                        {% endif %}
                    </td>
                </tr>
                <tr>
                    <td class="filename">
                        <a href="{{ path('jury_problem_testcase_fetch', {'probId': problem.probid, 'rank': testcase.rank, 'type': 'output'}) }}">
                            {{ testcase.downloadName }}.{{ extensionMapping.output }}
                        </a>
                    </td>
                    <td class="size">
                        {{ testcaseData[testcase.rank].output_size | printSize }}
                    </td>
                    <td class="md5 small">
                        {{ testcase.md5sumOutput }}
                    </td>
                    {% if allowEdit %}
                        <td><div class="input-group">
                            <label class="form-control text-truncate" for="update_output_{{testcase.rank}}" id="update_output_label_{{testcase.rank}}">new output file</label>
                            <input type="file" class="d-none custom-file-input" name="update_output[{{ testcase.rank }}]" id="update_output_{{testcase.rank}}">
                        </div></td>
                    {% endif %}
                    <td class="testimage">
                        {% if testcaseData[testcase.rank].image_size > 0 %}
                            <a href="{{ path('jury_problem_testcase_fetch', {'probId': problem.probid, 'rank': testcase.rank, 'type': 'image'}) }}">
                                <span class="filename">p{{ problem.probid }}.t{{ testcase.rank }}.{{ testcaseData[testcase.rank].image_type }}</span>
                            </a>
                            {% if allowEdit %}
                            &nbsp;
                            <div class="input-group">
                                <label class="form-control text-truncate" for="update_image_{{testcase.rank}}" id="update_imapge_label_{{testcase.rank}}">replace image</label>
                                <input type="file" class="d-none custom-file-input" name="update_image[{{ testcase.rank }}]" id="update_image_{{testcase.rank}}" accept="image/*">
                            </div>
                            {% endif %}
                        {% else %}
                            {% if allowEdit %}
                            <div class="input-group">
                                <label class="form-control text-truncate" for="update_image_{{testcase.rank}}" id="update_imapge_label_{{testcase.rank}}">add an image</label>
                                <input type="file" class="d-none custom-file-input" name="update_image[{{ testcase.rank }}]" id="update_image_{{testcase.rank}}" accept="image/*">
                            </div>
                            {% else %}
                            <span class="nodata">No image</span>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% endif %}

    {% if allowEdit %}
        <h2>Create new testcase</h2>

        <div class="row mb-2">
            <label class="col-sm-2 col-form-label" for="add_input">Input testdata</label>
            <div class="col-sm-4">
                <input type="file" class="form-control" name="add_input" id="add_input">
            </div>
        </div>

        <div class="row mb-2">
            <label class="col-sm-2 col-form-label" for="add_output">Output testdata</label>
            <div class="col-sm-4">
                <input type="file" class="form-control" name="add_output" id="add_output">
            </div>
        </div>

        <div class="row mb-2">
            <div class="col-sm-2"></div>
            <div class="col-sm-4">
                <div class="form-check">
                    <input type="checkbox" class="form-check-input" id="add_sample" name="add_sample">
                    <label class="form-check-label" for="add_sample">Sample testcase</label>
                </div>
            </div>
        </div>

        <div class="row mb-2">
            <label for="add_desc" class="col-sm-2 col-form-label">Description</label>
            <div class="col-sm-4">
                <textarea name="add_desc" id="add_desc" rows="5" class="form-control"></textarea>
            </div>
        </div>

        <div class="row mb-2">
            <label class="col-sm-2 col-form-label" for="add_image">Image</label>
            <div class="col-sm-4">
                <input type="file" class="form-control" accept="image/*" name="add_image" id="add_image">
            </div>
        </div>

        <input type="submit" class="btn btn-primary mt-3" value="Submit all changes">
    {% endif %}

    </form>

    <script>
        $(function() {
            $('.testcase-edit-description').on('click', function() {
                var $button = $(this);
                var $description = $button.parent().find('.testcase-description');
                var $descriptionInput = $button.parent().find('.testcase-description-field');

                if ($description.hasClass('d-none')) {
                    $description.removeClass('d-none');
                    $descriptionInput.addClass('d-none');
                    $button.text('Edit');
                    $descriptionInput.val($description.text());
                } else {
                    $description.addClass('d-none');
                    $descriptionInput.removeClass('d-none');
                    $button.text('Cancel');
                }
            });
            $('.custom-file-input').change(function(e) {
                let fileName = (e.target.files.length > 0) ? e.target.files[0].name : 'new file';
                $(this).prev().text(fileName);
            });
        });
    </script>

{% endblock %}

webapp/templates/jury/refresh_scoreboard.html.twig
<div class="alert alert-warning">
    <strong>Warning:</strong> Refresh scoreboard cache
    <hr>
    <p>{{ message }}</p>
    <form action="{{ path('jury_refresh_cache') }}" method="POST">
        {% if current_contest is not empty %}
            <input type="hidden" name="cid" value="{{ current_contest.cid }}"/>
        {% endif %}
        <input type="submit" name="refresh" value="Recalculate caches now" class="btn btn-primary"/>
    </form>
</div>

webapp/templates/jury/team_category_add.html.twig
{% extends "jury/base.html.twig" %}
{% import "jury/jury_macros.twig" as macros %}

{% block title %}Add category - {{ parent() }}{% endblock %}

{% block extrahead %}
    {{ parent() }}
    {{ macros.coloris_extrahead() }}
{% endblock %}

{% block content %}

    <h1>Add category</h1>

    {% include 'jury/partials/team_category_form.html.twig' %}

{% endblock %}