webapp/src/Entity/Team.php
<?php declare(strict_types=1);

namespace App\Entity;

use App\Controller\API\AbstractRestController as ARC;
use App\DataTransferObject\ImageFile;
use App\DataTransferObject\TeamLocation;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use OpenApi\Attributes as OA;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * All teams participating in the contest.
 */
#[ORM\Entity]
#[ORM\Table(options: ['collation' => 'utf8mb4_unicode_ci', 'charset' => 'utf8mb4'])]
#[ORM\Index(columns: ['affilid'], name: 'affilid')]
#[ORM\Index(columns: ['categoryid'], name: 'categoryid')]
#[ORM\UniqueConstraint(name: 'externalid', columns: ['externalid'], options: ['lengths' => [190]])]
#[ORM\UniqueConstraint(name: 'label', columns: ['label'])]
#[UniqueEntity(fields: 'externalid')]
class Team extends BaseApiEntity implements
    HasExternalIdInterface,
    AssetEntityInterface,
    ExternalIdFromInternalIdInterface,
    PrefixedExternalIdInterface
{
    final public const DONT_ADD_USER = 'dont-add-user';
    final public const CREATE_NEW_USER = 'create-new-user';
    final public const ADD_EXISTING_USER = 'add-existing-user';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(options: ['comment' => 'Team ID', 'unsigned' => true])]
    #[Serializer\SerializedName('teamid')]
    #[Serializer\Groups([ARC::GROUP_NONSTRICT])]
    protected ?int $teamid = null;

    #[ORM\Column(
        nullable: true,
        options: ['comment' => 'Team ID in an external system', 'collation' => 'utf8mb4_bin']
    )]
    #[Serializer\SerializedName('id')]
    protected ?string $externalid = null;

    #[ORM\Column(
        nullable: true,
        options: ['comment' => 'Team ID in the ICPC system', 'collation' => 'utf8mb4_bin']
    )]
    #[OA\Property(nullable: true)]
    #[Serializer\SerializedName('icpc_id')]
    protected ?string $icpcid = null;

    #[ORM\Column(
        nullable: true,
        options: ['comment' => 'Team label, for example the seat number', 'collation' => 'utf8mb4_bin']
    )]
    #[OA\Property(nullable: true)]
    protected ?string $label = null;

    #[ORM\Column(options: ['comment' => 'Team name', 'collation' => 'utf8mb4_bin'])]
    #[Assert\NotBlank]
    private string $name = '';

    #[ORM\Column(
        nullable: true,
        options: ['comment' => 'Team display name', 'collation' => 'utf8mb4_bin']
    )]
    #[OA\Property(nullable: true)]
    private ?string $display_name = null;

    #[ORM\Column(options: [
        'comment' => 'Whether the team is visible and operational',
        'default' => 1,
    ])]
    #[Serializer\Exclude]
    private bool $enabled = true;

    #[ORM\Column(
        name: 'publicdescription',
        type: 'text',
        nullable: true,
        options: ['comment' => 'Public team definition; for example: Team member names (freeform)']
    )]
    #[OA\Property(nullable: true)]
    #[Serializer\Groups([ARC::GROUP_NONSTRICT])]
    private ?string $publicDescription = null;

    #[ORM\Column(nullable: true, options: ['comment' => 'Physical location of team'])]
    #[OA\Property(nullable: true)]
    #[Serializer\Exclude]
    private ?string $location = null;

    #[ORM\Column(
        name: 'internalcomments',
        type: 'text',
        nullable: true,
        options: ['comment' => 'Internal comments about this team (jury only)']
    )]
    #[Serializer\Exclude]
    private ?string $internalComments = null;

    #[ORM\Column(
        type: 'decimal',
        precision: 32,
        scale: 9,
        nullable: true,
        options: ['comment' => 'Start time of last judging for prioritization', 'unsigned' => true]
    )]
    #[Serializer\Exclude]
    private string|float|null $judging_last_started = null;

    #[ORM\Column(options: ['comment' => 'Additional penalty time in minutes', 'default' => 0])]
    #[Serializer\Exclude]
    private int $penalty = 0;

    #[Serializer\Exclude]
    private string $addUserForTeam = self::DONT_ADD_USER;

    #[Assert\Regex('/^[a-z0-9@._-]+$/i', message: 'Only alphanumeric characters and _-@. are allowed')]
    #[Serializer\Exclude]
    private ?string $newUsername = null;

    #[Serializer\Exclude]
    private ?User $existingUser = null;

    #[Assert\File(mimeTypes: ['image/png', 'image/jpeg', 'image/svg+xml'], mimeTypesMessage: "Only PNG's, JPG's and SVG's are allowed")]
    #[Serializer\Exclude]
    private ?UploadedFile $photoFile = null;

    #[Serializer\Exclude]
    private bool $clearPhoto = false;

    #[ORM\ManyToOne(inversedBy: 'teams')]
    #[ORM\JoinColumn(name: 'affilid', referencedColumnName: 'affilid', onDelete: 'SET NULL')]
    #[Serializer\Exclude]
    private ?TeamAffiliation $affiliation = null;

    #[ORM\ManyToOne(inversedBy: 'teams')]
    #[ORM\JoinColumn(name: 'categoryid', referencedColumnName: 'categoryid', onDelete: 'CASCADE')]
    #[Serializer\Exclude]
    private ?TeamCategory $category = null;

    /**
     * @var Collection<int, Contest>
     */
    #[ORM\ManyToMany(targetEntity: Contest::class, mappedBy: 'teams')]
    #[Serializer\Exclude]
    private Collection $contests;

    /**
     * @var Collection<int, User>
     */
    #[ORM\OneToMany(mappedBy: 'team', targetEntity: User::class, cascade: ['persist'])]
    #[Assert\Valid]
    #[Serializer\Exclude]
    private Collection $users;

    /**
     * @var Collection<int, Submission>
     */
    #[ORM\OneToMany(mappedBy: 'team', targetEntity: Submission::class)]
    #[Serializer\Exclude]
    private Collection $submissions;

    /**
     * @var Collection<int, Clarification>
     */
    #[ORM\OneToMany(mappedBy: 'sender', targetEntity: Clarification::class)]
    #[Serializer\Exclude]
    private Collection $sent_clarifications;

    /**
     * @var Collection<int, Clarification>
     */
    #[ORM\OneToMany(mappedBy: 'recipient', targetEntity: Clarification::class)]
    #[Serializer\Exclude]
    private Collection $received_clarifications;

    /**
     * @var Collection<int, Clarification>
     */
    #[ORM\ManyToMany(targetEntity: Clarification::class)]
    #[ORM\JoinTable(name: 'team_unread')]
    #[ORM\JoinColumn(name: 'teamid', referencedColumnName: 'teamid', onDelete: 'CASCADE')]
    #[ORM\InverseJoinColumn(name: 'mesgid', referencedColumnName: 'clarid', onDelete: 'CASCADE')]
    #[Serializer\Exclude]
    private Collection $unread_clarifications;

    // This field gets filled by the team visitor with a data transfer
    // object that represents the team photo
    #[Serializer\Exclude]
    private ?ImageFile $photoForApi = null;

    public function setTeamid(int $teamid): Team
    {
        $this->teamid = $teamid;
        return $this;
    }

    public function getTeamid(): ?int
    {
        return $this->teamid;
    }

    public function setExternalid(?string $externalid): Team
    {
        $this->externalid = $externalid;
        return $this;
    }

    public function getExternalid(): ?string
    {
        return $this->externalid;
    }

    public function setIcpcid(?string $icpcid): Team
    {
        $this->icpcid = $icpcid;

        return $this;
    }

    public function getIcpcId(): ?string
    {
        return $this->icpcid;
    }

    public function setLabel(?string $label): Team
    {
        $this->label = $label;
        return $this;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setName(string $name): Team
    {
        $this->name = $name;
        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setDisplayName(?string $display_name): self
    {
        $this->display_name = $display_name;
        return $this;
    }

    public function getDisplayName(): ?string
    {
        return $this->display_name;
    }

    public function getEffectiveName(): string
    {
        return $this->getDisplayName() ?? $this->getName();
    }

    public function getShortDescription(): string
    {
        return $this->getEffectiveName();
    }

    public function setEnabled(bool $enabled): Team
    {
        $this->enabled = $enabled;
        return $this;
    }

    public function getEnabled(): bool
    {
        return $this->enabled;
    }

    public function setPublicDescription(?string $publicDescription): Team
    {
        $this->publicDescription = $publicDescription;
        return $this;
    }

    public function getPublicDescription(): ?string
    {
        return $this->publicDescription;
    }

    public function setLocation(?string $location): Team
    {
        $this->location = $location;
        return $this;
    }

    public function getLocation(): ?string
    {
        return $this->location;
    }

    #[Serializer\Groups([ARC::GROUP_NONSTRICT])]
    #[Serializer\VirtualProperty]
    #[Serializer\SerializedName('location')]
    public function getLocationForApi(): ?TeamLocation
    {
        return $this->location ? new TeamLocation($this->location) : null;
    }

    public function setInternalComments(?string $comments): Team
    {
        $this->internalComments = $comments;
        return $this;
    }

    public function getInternalComments(): ?string
    {
        return $this->internalComments;
    }

    public function setJudgingLastStarted(string|float $judgingLastStarted): Team
    {
        $this->judging_last_started = $judgingLastStarted;
        return $this;
    }

    public function getJudgingLastStarted(): string|float
    {
        return $this->judging_last_started;
    }

    public function setPenalty(int $penalty): Team
    {
        $this->penalty = $penalty;
        return $this;
    }

    /**

webapp/src/Controller/Team/ClarificationController.php
<?php declare(strict_types=1);

namespace App\Controller\Team;

use App\Controller\BaseController;
use App\Entity\Clarification;
use App\Entity\Contest;
use App\Entity\Problem;
use App\Entity\Team;
use App\Form\Type\TeamClarificationType;
use App\Service\ConfigurationService;
use App\Service\DOMJudgeService;
use App\Service\EventLogService;
use App\Utils\Utils;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\Query\Expr\Join;
use Symfony\Component\ExpressionLanguage\Expression;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpKernel\KernelInterface;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

#[IsGranted('ROLE_TEAM')]
#[IsGranted(
    new Expression('user.getTeam() !== null'),
    message: 'You do not have a team associated with your account. '
)]
#[Route(path: '/team')]
class ClarificationController extends BaseController
{
    public function __construct(
        DOMJudgeService $dj,
        protected readonly ConfigurationService $config,
        EntityManagerInterface $em,
        protected readonly EventLogService $eventLogService,
        protected readonly FormFactoryInterface $formFactory,
        KernelInterface $kernel,
    ) {
        parent::__construct($em, $eventLogService, $dj, $kernel);
    }

    /**
     * @throws NonUniqueResultException
     */
    #[Route(path: '/clarifications/{clarId<\d+>}', name: 'team_clarification')]
    public function viewAction(Request $request, int $clarId): Response
    {
        $categories = $this->config->get('clar_categories');
        $user       = $this->dj->getUser();
        $team       = $user->getTeam();
        $contest    = $this->dj->getCurrentContest($team->getTeamid());
        /** @var Clarification|null $clarification */
        $clarification = $this->em->createQueryBuilder()
            ->from(Clarification::class, 'c')
            ->leftJoin('c.problem', 'p')
            ->leftJoin('c.contest', 'co')
            ->leftJoin('p.contest_problems', 'cp', Join::WITH, 'cp.contest = :contest')
            ->select('c, p, co')
            ->andWhere('c.contest = :contest')
            ->andWhere('c.clarid = :clarId')
            ->setParameter('contest', $contest)
            ->setParameter('clarId', $clarId)
            ->getQuery()
            ->getOneOrNullResult();

        $formData = [];
        if ($clarification) {
            if ($clarification->getProblem()) {
                $formData['subject'] = sprintf('%d-%d', $clarification->getContest()->getCid(), $clarification->getProblem()->getProbid());
            } else {
                $formData['subject'] = sprintf('%d-%s', $clarification->getContest()->getCid(), $clarification->getCategory());
            }

            $formData['message'] = "> " . str_replace("\n", "\n> ", Utils::wrapUnquoted($clarification->getBody())) . "\n\n";
        }
        $form = $this->formFactory
            ->createBuilder(TeamClarificationType::class, $formData)
            ->setAction($this->generateUrl('team_clarification', ['clarId' => $clarId]))
            ->getForm();

        $form->remove('subject');

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->newClarificationHelper($form, $contest, $team);
            return $this->redirectToRoute('team_index');
        }

        if ($clarification === null) {
            throw new NotFoundHttpException(sprintf('Clarification %d not found', $clarId));
        }

        if (!$team->canViewClarification($clarification)) {
            throw new HttpException(401, 'Permission denied');
        }

        // Get the "parent" message if we have one.
        if ($clarification->getInReplyTo()) {
            $clarification = $clarification->getInReplyTo();
        }

        // Mark clarification as read.
        $team->removeUnreadClarification($clarification);
        foreach ($clarification->getReplies() as $reply) {
            $team->removeUnreadClarification($reply);
        }
        $this->em->flush();

        $data = [
            'clarification' => $clarification,
            'team' => $team,
            'categories' => $categories,
            'form' => $form->createView(),
        ];

        if ($request->isXmlHttpRequest()) {
            return $this->render('team/clarification_modal.html.twig', $data);
        } else {
            return $this->render('team/clarification.html.twig', $data);
        }
    }

    #[Route(path: '/clarifications/add', name: 'team_clarification_add')]
    public function addAction(Request $request): Response
    {
        $categories = $this->config->get('clar_categories');
        $user       = $this->dj->getUser();
        $team       = $user->getTeam();
        $contest    = $this->dj->getCurrentContest($team->getTeamid());

        $formData = [];
        $form     = $this->formFactory
            ->createBuilder(TeamClarificationType::class, $formData)
            ->setAction($this->generateUrl('team_clarification_add'))
            ->getForm();

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->newClarificationHelper($form, $contest, $team);
            return $this->redirectToRoute('team_index');
        }

        $data = [
            'categories' => $categories,
            'form' => $form->createView(),
        ];

        if ($request->isXmlHttpRequest()) {
            return $this->render('team/clarification_add_modal.html.twig', $data);
        } else {
            return $this->render('team/clarification_add.html.twig', $data);
        }
    }

    /**
     * @throws NonUniqueResultException
     */
    private function newClarificationHelper(
        FormInterface $form,
        ?Contest $contest,
        Team $team
    ): void {
        $formData = $form->getData();
        // First part will always be the contest ID, as Symfony will validate this.
        [, $problemId] = explode('-', $formData['subject']);
        $problem = null;
        $category = null;
        $queue = null;
        if (!ctype_digit($problemId)) {
            $category = $problemId;
        } else {
            $problem = $this->em->getRepository(Problem::class)->find($problemId);
            $queue = $this->config->get('clar_default_problem_queue');
            if ($queue === "") {
                $queue = null;
            }
        }

        $newClarification = new Clarification();
        $newClarification
            ->setContest($contest)
            ->setSubmittime(Utils::now())
            ->setSender($team)
            ->setProblem($problem)
            ->setCategory($category)
            ->setQueue($queue)
            ->setBody($formData['message']);

        $this->em->persist($newClarification);
        $this->em->flush();

        $this->dj->auditlog('clarification', $newClarification->getClarid(), 'added', null, null,
            $contest->getCid());
        $this->eventLogService->log('clarification', $newClarification->getClarid(), 'create', $contest->getCid());

        $this->addFlash('success', 'Clarification sent to the jury');
    }
}

webapp/templates/team/partials/clarification.html.twig
<div class="card mb-3">
    <div class="card-header">
        <div class="row">
            <div class="col-sm">
                Subject:
                {% if clarification.problem %}
                    Problem {{ clarification.contestProblem.shortname }}: {{ clarification.problem.name }}
                {% elseif clarification.category %}
                    {{ categories[clarification.category]|default('general') }}
                {% else %}
                    General issue
                {% endif %}
            </div>
            <div class="col-sm text-muted text-end">{{ clarification.submittime | printtimeHover(clarification.contest) }}</div>
        </div>
    </div>
    <div class="card-body">
        <div class="card-title">
            <div class="row">
                <div class="col-sm">
                    From:
                    {% if clarification.sender is not empty %}
                        {{ clarification.sender.effectiveName }} (t{{ clarification.sender.teamid }})
                    {% else %}
                        Jury
                    {% endif %}
                </div>
                <div class="col-sm">To:
                    {% if clarification.recipient is not empty %}
                        {{ clarification.recipient.effectiveName }} (t{{ clarification.recipient.teamid }})
                    {% elseif clarification.sender is not null %}
                        Jury
                    {% else %}
                        <strong>All</strong>
                    {% endif %}
                </div>
            </div>
        </div>

        <hr/>

        <div class="card-text">
            {{ clarification.body | markdown_to_html | sanitize_html('app.clarification_sanitizer') }}
        </div>
    </div>
</div>

webapp/templates/team/partials/clarification_content.html.twig
<div class="container clarificationform">
    {% include 'team/partials/clarification.html.twig' with {clarification: clarification } %}
    {% for reply in clarification.replies | filter(reply => team.canViewClarification(reply)) %}
        {% include 'team/partials/clarification.html.twig' with {clarification: reply } %}
    {% endfor %}
</div>

<div class="collapse {% if not form.vars.valid %}show{% endif%} mt-3 container clarificationform" id="collapsereplyform">
    <div class="card card-body">
        {{ form_start(form) }}
        {{ form_row(form.recipient) }}
        <div class="mb-3">
            {{ form_widget(form.message) }}
            {{ form_errors(form.message) }}
        </div>
        <div class="mb-3">
            <div class="card">
                <div class="card-body">
                    <label class="rendered-preview-badge">rendered preview</label>
                    <div id="messagepreview">Start typing to see a preview of your message</div>
                </div>
            </div>
        </div>
        {{ form_end(form) }}
    </div>
</div>

webapp/templates/team/partials/clarification_list.html.twig
<div class="table-wrapper">
    <table class="data-table table table-striped table-hover table-sm" style="width:100%;">
        <thead class="thead-light">
        <tr>
            <th scope="col">time</th>
            <th scope="col">from</th>
            <th scope="col">to</th>
            <th scope="col">subject</th>
            <th scope="col">text</th>
        </tr>
        </thead>
        <tbody>
        {%- for clarification in clarifications %}
            {%- set link = path('team_clarification', {clarId: clarification.clarid}) %}

            <tr class="{% if team.unreadClarifications.contains(clarification) %}unseen{% endif %}">
                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" href="{{ link }}">
                        {{ clarification.submittime | printtime(null, clarification.contest) }}
                    </a>
                </td>
                {%- if clarification.sender is null %}
                    {%- set sender = 'Jury' %}
                    {%- if clarification.recipient is null %}
                        {%- set recipient = 'All' %}
                    {%- else %}
                        {%- set recipient = clarification.recipient.effectiveName %}
                    {%- endif %}
                {%- else %}
                    {%- set recipient = 'Jury' %}
                    {%- set sender = clarification.sender.effectiveName %}
                {%- endif %}

                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" href="{{ link }}" title="{{ sender }}">
                        {{ sender | u.truncate(teamname_max_length, '…') }}
                    </a>
                </td>
                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" href="{{ link }}" title="{{ recipient }}">
                        {{ recipient | u.truncate(teamname_max_length, '…') }}
                    </a>
                </td>
                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" href="{{ link }}">
                        {%- if clarification.problem -%}
                            problem {{ clarification.contestProblem | problemBadge -}}
                        {%- elseif clarification.category -%}
                            {{- categories[clarification.category]|default('general') -}}
                        {%- else -%}
                            general
                        {%- endif -%}
                    </a>
                </td>

                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" href="{{ link }}">
                        {{ clarification.summary }}
                    </a>
                </td>
            </tr>
        {%- endfor %}

        </tbody>
    </table>
</div>

webapp/templates/team/partials/index_content.html.twig
{% if contest is empty %}
    <h1 id="teamwelcome" class="text-center">Welcome team <span id="teamwelcometeam">{{ team.effectiveName }}</span>!</h1>
    <h2 id="contestnotstarted" class="text-center">There's no active contest for you (yet).</h2>
{% elseif not contest.freezeData.started %}
    <h1 id="teamwelcome" class="text-center">Welcome team <span id="teamwelcometeam">{{ team.effectiveName }}</span>!</h1>
    <h2 id="contestnotstarted" class="text-center">
        Contest {{ contest | printContestStart }}
    </h2>
{% else %}

    <div id="teamscoresummary">
        {% set displayRank = not contest.freezeData.showFrozen %}
        {% include 'partials/scoreboard_table.html.twig' with {displayRank: displayRank, jury: false, public: false} %}
    </div>

    <div class="mt-4" data-flash-messages>
        {% include 'partials/messages.html.twig' %}
        {% if not contest.allowSubmit %}
            {% include 'partials/alert.html.twig' with {'type': 'danger', 'message': 'Submissions (temporarily) disabled.'} %}
        {% endif %}
    </div>

    <div class="row">
        <div class="col">
            <h1 class="teamoverview">Submissions</h1>

            {% include 'team/partials/submission_list.html.twig' %}
        </div>
        <div class="col">
            <h1 class="teamoverview">Clarifications</h1>
            {% if clarifications is empty %}
                <p class="nodata">No clarifications.</p>
            {% else %}
                {% include 'team/partials/clarification_list.html.twig' with {clarifications: clarifications} %}
            {% endif %}

            <h1 class="teamoverview">Clarification Requests</h1>
            {% if clarificationRequests is empty %}
                <p class="nodata">No clarification request.</p>
            {% else %}
                {% include 'team/partials/clarification_list.html.twig' with {clarifications: clarificationRequests} %}
            {% endif %}

            <div class="m-1">
                <a href="{{ path('team_clarification_add') }}" class="btn btn-secondary btn-sm" data-ajax-modal data-ajax-modal-after="initModalClarificationPreviewAdd">
                    request clarification
                </a>
            </div>
        </div>
    </div>
{% endif %}

{% if ajax is defined and ajax %}
    {% include 'partials/scoreboard_progress_bar.html.twig' with {margin: -9, contest: current_team_contest} %}
{% endif %}

webapp/templates/team/partials/submission_list.html.twig
{# Render a list of submissions for a team page #}
{# @var submission \App\Entity\Submission #}

{% if submissions is empty %}
    <div class="alert alert-warning">No submissions</div>
{% else %}
    <table class="data-table table table-hover table-striped table-sm submissions-table">
        <thead class="thead-light">
        <tr>
            <th scope="col">time</th>
            <th scope="col">problem</th>
            <th scope="col">lang</th>
            <th scope="col">result</th>
            {% if contest.getRuntimeAsScoreTiebreaker() %}
                <th scope="col">runtime</th>
            {% endif %}
            {% if allowDownload %}
                <th scope="col"></th>
            {% endif %}
        </tr>
        </thead>
        <tbody>
        {%- for submission in submissions %}
            {% set link = null %}
            {% if (submission.submittime < current_team_contest.endtime or showTooLateResult) and submission.result and submission.judgings.first is not empty and submission.judgings.first.result is not empty and (not verificationRequired or submission.judgings.first.verified) %}
                {% set link = path('team_submission', {submitId: submission.submitid}) %}
            {% endif %}

            {% set classes = '' %}
            {% if not submission.valid %}
                {% set classes = classes ~ ' ignore' %}
            {% endif %}
            {% if submission.judgings.first is empty or not submission.judgings.first.seen %}
                {% set classes = classes ~ ' unseen' %}
            {% endif %}
            <tr class="{{ classes }}">
                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" {% if link %}href="{{ link }}"{% endif %}>
                        {{ submission.submittime | printtime(null, submission.contest) }}
                    </a>
                </td>
                <td class="probid">
                    <a data-ajax-modal data-ajax-modal-after="markSeen" {% if link %}href="{{ link }}"{% endif %} title="{{ submission.problem.name }}">
                        {{ submission.contestProblem | problemBadge }}
                    </a>
                </td>
                <td class="langid">
                    <a data-ajax-modal data-ajax-modal-after="markSeen" {% if link %}href="{{ link }}"{% endif %} title="{{ submission.language.name }}">
                        {{ submission.language.langid }}
                    </a>
                </td>
                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" {% if link %}href="{{ link }}"{% endif %}>
                        {%- if submission.submittime > submission.contest.endtime %}
                            {{ 'too-late' | printResult }} 
                        {%- endif %}
                        {%- if submission.submittime <= submission.contest.endtime or showTooLateResult %}
                            {%- if submission.submittime > submission.contest.endtime %}
                                /
                            {% endif %}
                            {%- if submission.judgings.first is empty or submission.judgings.first.result is empty %}
                                {{- '' | printResult -}}
                            {%- elseif verificationRequired and not submission.judgings.first.verified %}
                                {{- '' | printResult -}}
                            {%- else %}
                                {{- submission.judgings.first.result | printResult -}}
                            {%- endif %}
                        {%- endif %}
                    </a>
                </td>
        {% if contest.getRuntimeAsScoreTiebreaker() %}
                <td>
                    <a data-ajax-modal data-ajax-modal-after="markSeen" {% if link %}href="{{ link }}"{% endif %}>
                        {% if link and submission.getResult()=='correct' %}
                            {{ "%0.3f s" | format(submission.judgings.first.getMaxRuntime()) }}
                        {% else %}
                            -
                        {% endif %}
                    </a>
                </td>
        {% endif %}
        {% if allowDownload %}
                <td>
                    <a title="Download submission ZIP" aria-label="download submission zip" class="btn btn-light" href="{{ path('team_submission_download', {'submitId': submission.submitid}) }}">
                        <i class="fa fa-file-archive"></i>
                    </a>
                </td>
        {% endif %}
            </tr>
        {%- endfor %}
        </tbody>
    </table>
{% endif %}